language: pyathon

python:
  - 3.7


# install dependencies
install:
  - pip install -r requirements.txt

before_script:
  - python manage.py makemigrations --check --dry-run
  - python manage.py migrate
  - python manage.py collectstatic --noinput

script:
  - black --check --diff .
  - flake8 .
  - coverage run manage.py test

after_success:
  - coveralls